// Status=edited

Source code for _WSJT-X_ is available from a public repository at
{devrepo}. To compile the program, at a minimum you must install the
following packages:

- Git
- Qt 5.2 or later
- g++ 4.8 or later
- gfortran 4.8 or later
- fftw3
- MinGW (for Windows only)

For Ubuntu 24.04 LTS and Ubuntu 25.10, the following command installs
the required build tools and development packages:

=====
sudo apt-get update
sudo apt-get install build-essential cmake gfortran git asciidoc \
     qtbase5-dev qtmultimedia5-dev libqt5serialport5-dev \
     qttools5-dev qttools5-dev-tools libfftw3-dev libboost-all-dev \
     libusb-1.0-0-dev portaudio19-dev
=====

Source code for _WSJT-X_ v{VERSION} can be downloaded with the command:

=====
git clone git://git.code.sf.net/p/wsjt/wsjtx
cd wsjtx
git checkout wsjtx-{VERSION}
=====

and for the current development branch:

=====
git clone git://git.code.sf.net/p/wsjt/wsjtx
=====

If you are interested in contributing to the development and
documentation of _WSJT_ and its sister programs, please join the
developer's email list {devmail} and let us know of your areas of
interest.
